# Note:  This is an example config, see habitat_baselines/config/pointnav/ppo_pointnav.yaml
# for better hyperparameters for actual training
VERSION: Habitat_web_pointnav
BASE_TASK_CONFIG_PATH: "pointnav_mp3d_il.yaml"
IL_TRAINER_NAME: "ILEnvTrainer"
ENV_NAME: NavRLEnv
SIMULATOR_GPU_ID: 7
TORCH_GPU_ID: [0,1,2,3]

DISTRIBUTED: True
CUDNN:
  BENCHMARK: True
  DETERMINISTIC: False
  ENABLED: True

NUM_PROCESSES: 4
NUM_VAL_PROCESSES: 0

VIDEO_OPTION: [] #["disk"] [""tensorboard""]
# To evaluate on all episodes, set this to -1
TEST_EPISODE_COUNT: 10
# EVAL_CKPT_PATH_DIR: "data/ckpt.22.pth"
SHOW_TOP_DOWN_MAP: False

# OUTPUT_LOG_DIR: data/objectnav/logs
LOG_INTERVAL: 20
CHECKPOINT_INTERVAL: 400
VIS_INTERVAL: 25

SENSORS: ["DEPTH_SENSOR", "RGB_SENSOR"]
#EVAL_RESUTLS_DIR: "data/objectnav/results/"
# EVAL_SAVE_RESULTS: True
# EVAL_SAVE_RESULTS_INTERVAL: 50
# NUM_UPDATES: 1000
EVAL:
  SPLIT: "val"


POLICY: "PointNavResNetPolicy"
WRAPPER: 'BaseGraphWrapper'

MODEL:
  DEPTH_ENCODER:
    ddppo_checkpoint: "./pretrained_models//gibson-2plus-resnet50.pth"

  STATE_ENCODER:
    hidden_size: 512
    num_recurrent_layers: 2
    rnn_type: 'GRU'

memory:
  memory_size: 501

RL:
  PPO:
    use_linear_lr_decay: True
    use_linear_clip_decay: False
    max_grad_norm: 0.2
    num_mini_batch: 1
    num_steps: 16

BC:
  CKPT: ''
  max_epoch: 25
  USE_IW: True
  lr: 0.001
  eps: 1.0e-5
  max_grad_norm: 0.2
  max_demo_length: 100